const heatspots = [
  'Austin Texas',
  'District of Columbia',
  'Seattle Washington',
  'Milwaukee Wisconsin',
  'Raleigh North Carolina',
  'Richmond Virginia',
  'San Jose California',
  'New York',
  'Los Angeles California',
  'Chicago',
  'Houston Texas',
  'Phoenix Arizona',
  'Philadelphia',
  'San Antonio Texas',
  'San Diego California',
  'Dallas Texas',
  'Jacksonville Florida',
  'Columbus Ohio',
  'Cleveland Ohio',
  'Indianapolis Indiana',
  'Charlotte North Carolina',
  'San Francisco',
  'Denver Colorado',
  'Nashville Tennessee',
  'Oklahoma City',
  'Boston Massachusetts',
  'Portland Oregon',
  'Las Vegas Nevada',
  'Detroit Michigan',
  'Baltimore Maryland',
  'Atlanta Georgia',
  'Omaha Nebraska',
  'Salt Lake City Utah',
  'Pittsburgh Pennsylvania',
  'Minneapolis Minnesota',
  'St. Louis Missouri',
  'Kansas City',
  'New Orleans Louisiana',
  'Vancouver',
  'Toronto',
  'Ottawa',
  'Montreal',
  'Quebec City',
  'Mexico City',
];

export default heatspots;
